### ISSUE TITLE
 device.deviceAddress is null in the onActivityResult of DeviceDetailsFragment.java

### ISSUE THREAD

**Issue by dingusagar** [life0fun/wifi-direct-chat#5]
2 phones got connected successfully. But when I try to launch the gallery and click an image , the app crashes. Please help

The error message tells that the device.deviceAddress is null in the onActivityResult of DeviceDetailsFragment.java
[--------code-snippet----
@Override
	public void onActivityResult(int requestCode, int resultCode, Intent data) {

		String localIP = Utils.getLocalIPAddress();
		// Trick to find the ip in the file /proc/net/arp
		String client_mac_fixed = new String(device.deviceAddress).replace("99", "19");
		String clientIP = Utils.getIPFromMac(client_mac_fixed);

----------------------------------------]

[ ERROR MESSAGE ] 

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.android.wifidirect, PID: 26275
                  java.lang.RuntimeException: Failure delivering result ResultInfo{who=android:fragment:1, request=20, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:15319 flg=0x1 }} to activity {com.example.android.wifidirect/com.example.android.wifidirect.WiFiDirectActivity}: java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.net.wifi.p2p.WifiP2pDevice.deviceAddress' on a null object reference
                      at android.app.ActivityThread.deliverResults(ActivityThread.java:3588)
                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:3631)
                      at android.app.ActivityThread.access$1300(ActivityThread.java:151)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5268)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
                   Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.net.wifi.p2p.WifiP2pDevice.deviceAddress' on a null object reference
                      at com.example.android.wifidirect.DeviceDetailFragment.onActivityResult(DeviceDetailFragment.java:128)
                      at android.app.Activity.dispatchActivityResult(Activity.java:6239)
                      at android.app.ActivityThread.deliverResults(ActivityThread.java:3584)
                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:3631) 
                      at android.app.ActivityThread.access$1300(ActivityThread.java:151) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:135) 
                      at android.app.ActivityThread.main(ActivityThread.java:5268) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)

**Comment by HargunCoder** [comment]
Sir how did you resolved this issue
